name: runSeliniumTestt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

     strategy:
      fail-fast: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build and Run Tests
        run: |
          mvn clean test

      - name: Upload TestNG Report (test-output folder)
        uses: actions/upload-artifact@v4
        with:
          name: TestNG-Report
          path: test-output/

      - name: Upload TestNG Report (surefire-reports folder)
        uses: actions/upload-artifact@v4
        with:
          name: Surefire-Reports
          path: target/surefire-reports/


