name: Run Selenium Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Maven
      run: sudo apt-get install -y maven

    - name: Run Maven Tests
      run: mvn test
      continue-on-error: true  # Important: continue even if test fails

    - name: Upload Extent Reports
      if: always()  # Always run this step even if previous step fails
      uses: actions/upload-artifact@v4
      with:
        name: ExtentReports
        path: test-output/  # path where ExtentReport.html is generated
